import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

const sans = GeistSans;
const mono = GeistMono;

import { MicrophoneProvider } from "@/contexts/MicrophoneContext";
import { DeepgramProvider } from "@/contexts/DeepgramContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans.className} ${mono.className} antialiased`}>
        <DeepgramProvider>
          <MicrophoneProvider>{children}</MicrophoneProvider>
        </DeepgramProvider>
      </body>
    </html>
  );
}
